
version: "3"

# TODO hide ports

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_SERVER_ID=1

  kafka:
    image: confluentinc/cp-kafka:7.2.0
    ports:
      - "39092:39092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_DOCKER://kafka:29092, PLAINTEXT_LOCAL://localhost:39092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT_DOCKER:PLAINTEXT,PLAINTEXT_LOCAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_DOCKER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes:
      - ./data:/var/lib/kafka/data/
    depends_on:
      - zookeeper

  init-kafka:
    image: confluentinc/cp-kafka:7.2.0
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      kafka-topics --bootstrap-server kafka:29092 --list
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic weather --replication-factor 1 --partitions 1
      echo -e 'Created topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "

  ksql:
    image: confluentinc/cp-ksqldb-server:7.2.0
    ports:
      - "8088:8088"
    environment:
      - KSQL_BOOTSTRAP_SERVERS=kafka:29092
      - KSQL_LISTENERS=http://0.0.0.0:8088/
      - KSQL_KSQL_SERVICE_ID=ksql_service_2_
    depends_on:
      - kafka

# https://docs.confluent.io/platform/current/installation/docker/config-reference.html#zk-configuration
